API = {
    "cn": "https://cn-apia.coolkit.cn",
    "as": "https://as-apia.coolkit.cc",
    "us": "https://us-apia.coolkit.cc",
    "eu": "https://eu-apia.coolkit.cc",
}

REGIONS = {
    "+93": ("Afghanistan", "as"),
    "+355": ("Albania", "eu"),
    "+213": ("Algeria", "eu"),
    "+376": ("Andorra", "eu"),
    "+244": ("Angola", "eu"),
    "+1264": ("Anguilla", "us"),
    "+1268": ("Antigua and Barbuda", "as"),
    "+54": ("Argentina", "us"),
    "+374": ("Armenia", "as"),
    "+297": ("Aruba", "eu"),
    "+247": ("Ascension", "eu"),
    "+61": ("Australia", "us"),
    "+43": ("Austria", "eu"),
    "+994": ("Azerbaijan", "as"),
    "+1242": ("Bahamas", "us"),
    "+973": ("Bahrain", "as"),
    "+880": ("Bangladesh", "as"),
    "+1246": ("Barbados", "us"),
    "+375": ("Belarus", "eu"),
    "+32": ("Belgium", "eu"),
    "+501": ("Belize", "us"),
    "+229": ("Benin", "eu"),
    "+1441": ("Bermuda", "as"),
    "+591": ("Bolivia", "us"),
    "+387": ("Bosnia and Herzegovina", "eu"),
    "+267": ("Botswana", "eu"),
    "+55": ("Brazil", "us"),
    "+673": ("Brunei", "as"),
    "+359": ("Bulgaria", "eu"),
    "+226": ("Burkina Faso", "eu"),
    "+257": ("Burundi", "eu"),
    "+855": ("Cambodia", "as"),
    "+237": ("Cameroon", "eu"),
    "+238": ("Cape Verde Republic", "eu"),
    "+1345": ("Cayman Islands", "as"),
    "+236": ("Central African Republic", "eu"),
    "+235": ("Chad", "eu"),
    "+56": ("Chile", "us"),
    "+86": ("China", "cn"),
    "+57": ("Colombia", "us"),
    "+682": ("Cook Islands", "us"),
    "+506": ("Costa Rica", "us"),
    "+385": ("Croatia", "eu"),
    "+53": ("Cuba", "us"),
    "+357": ("Cyprus", "eu"),
    "+420": ("Czech", "eu"),
    "+243": ("Democratic Republic of Congo", "eu"),
    "+45": ("Denmark", "eu"),
    "+253": ("Djibouti", "eu"),
    "+1767": ("Dominica", "as"),
    "+1809": ("Dominican Republic", "us"),
    "+670": ("East Timor", "as"),
    "+684": ("Eastern Samoa (US)", "us"),
    "+593": ("Ecuador", "us"),
    "+20": ("Egypt", "eu"),
    "+503": ("El Salvador", "us"),
    "+372": ("Estonia", "eu"),
    "+251": ("Ethiopia", "eu"),
    "+298": ("Faroe Islands", "eu"),
    "+679": ("Fiji", "us"),
    "+358": ("Finland", "eu"),
    "+33": ("France", "eu"),
    "+594": ("French Guiana", "us"),
    "+689": ("French Polynesia", "as"),
    "+241": ("Gabon", "eu"),
    "+220": ("Gambia", "eu"),
    "+995": ("Georgia", "as"),
    "+49": ("Germany", "eu"),
    "+233": ("Ghana", "eu"),
    "+350": ("Gibraltar", "eu"),
    "+30": ("Greece", "eu"),
    "+299": ("Greenland", "us"),
    "+1473": ("Grenada", "as"),
    "+590": ("Guadeloupe", "us"),
    "+1671": ("Guam", "us"),
    "+502": ("Guatemala", "us"),
    "+240": ("Guinea", "eu"),
    "+224": ("Guinea", "eu"),
    "+592": ("Guyana", "us"),
    "+509": ("Haiti", "us"),
    "+504": ("Honduras", "us"),
    "+852": ("Hong Kong, China", "as"),
    "+36": ("Hungary", "eu"),
    "+354": ("Iceland", "eu"),
    "+91": ("India", "as"),
    "+62": ("Indonesia", "as"),
    "+98": ("Iran", "as"),
    "+353": ("Ireland", "eu"),
    "+269": ("Islamic Federal Republic of Comoros", "eu"),
    "+972": ("Israel", "as"),
    "+39": ("Italian", "eu"),
    "+225": ("Ivory Coast", "eu"),
    "+1876": ("Jamaica", "us"),
    "+81": ("Japan", "as"),
    "+962": ("Jordan", "as"),
    "+254": ("Kenya", "eu"),
    "+975": ("Kingdom of Bhutan", "as"),
    "+383": ("Kosovo", "eu"),
    "+965": ("Kuwait", "as"),
    "+996": ("Kyrgyzstan", "as"),
    "+856": ("Laos", "as"),
    "+371": ("Latvia", "eu"),
    "+961": ("Lebanon", "as"),
    "+266": ("Lesotho", "eu"),
    "+231": ("Liberia", "eu"),
    "+218": ("Libya", "eu"),
    "+423": ("Liechtenstein", "eu"),
    "+370": ("Lithuania", "eu"),
    "+352": ("Luxembourg", "eu"),
    "+853": ("Macau, China", "as"),
    "+261": ("Madagascar", "eu"),
    "+265": ("Malawi", "eu"),
    "+60": ("Malaysia", "as"),
    "+960": ("Maldives", "as"),
    "+223": ("Mali", "eu"),
    "+356": ("Malta", "eu"),
    "+596": ("Martinique", "us"),
    "+222": ("Mauritania", "eu"),
    "+230": ("Mauritius", "eu"),
    "+52": ("Mexico", "us"),
    "+373": ("Moldova", "eu"),
    "+377": ("Monaco", "eu"),
    "+976": ("Mongolia", "as"),
    "+382": ("Montenegro", "as"),
    "+1664": ("Montserrat", "as"),
    "+212": ("Morocco", "eu"),
    "+258": ("Mozambique", "eu"),
    "+95": ("Myanmar", "as"),
    "+264": ("Namibia", "eu"),
    "+977": ("Nepal", "as"),
    "+31": ("Netherlands", "eu"),
    "+599": ("Netherlands Antilles", "as"),
    "+687": ("New Caledonia", "as"),
    "+64": ("New Zealand", "us"),
    "+505": ("Nicaragua", "us"),
    "+227": ("Niger", "eu"),
    "+234": ("Nigeria", "eu"),
    "+47": ("Norway", "eu"),
    "+968": ("Oman", "as"),
    "+92": ("Pakistan", "as"),
    "+970": ("Palestine", "as"),
    "+507": ("Panama", "us"),
    "+675": ("Papua New Guinea", "as"),
    "+595": ("Paraguay", "us"),
    "+51": ("Peru", "us"),
    "+63": ("Philippines", "as"),
    "+48": ("Poland", "eu"),
    "+351": ("Portugal", "eu"),
    "+974": ("Qatar", "as"),
    "+242": ("Republic of Congo", "eu"),
    "+964": ("Republic of Iraq", "as"),
    "+389": ("Republic of Macedonia", "eu"),
    "+262": ("Reunion", "eu"),
    "+40": ("Romania", "eu"),
    "+7": ("Russia", "eu"),
    "+250": ("Rwanda", "eu"),
    "+1869": ("Saint Kitts and Nevis", "as"),
    "+1758": ("Saint Lucia", "us"),
    "+1784": ("Saint Vincent", "as"),
    "+378": ("San Marino", "eu"),
    "+239": ("Sao Tome and Principe", "eu"),
    "+966": ("Saudi Arabia", "as"),
    "+221": ("Senegal", "eu"),
    "+381": ("Serbia", "eu"),
    "+248": ("Seychelles", "eu"),
    "+232": ("Sierra Leone", "eu"),
    "+65": ("Singapore", "as"),
    "+421": ("Slovakia", "eu"),
    "+386": ("Slovenia", "eu"),
    "+27": ("South Africa", "eu"),
    "+82": ("South Korea", "as"),
    "+34": ("Spain", "eu"),
    "+94": ("Sri Lanka", "as"),
    "+249": ("Sultan", "eu"),
    "+597": ("Suriname", "us"),
    "+268": ("Swaziland", "eu"),
    "+46": ("Sweden", "eu"),
    "+41": ("Switzerland", "eu"),
    "+963": ("Syria", "as"),
    "+886": ("Taiwan, China", "as"),
    "+992": ("Tajikistan", "as"),
    "+255": ("Tanzania", "eu"),
    "+66": ("Thailand", "as"),
    "+228": ("Togo", "eu"),
    "+676": ("Tonga", "us"),
    "+1868": ("Trinidad and Tobago", "us"),
    "+216": ("Tunisia", "eu"),
    "+90": ("Turkey", "as"),
    "+993": ("Turkmenistan", "as"),
    "+1649": ("Turks and Caicos", "as"),
    "+44": ("UK", "eu"),
    "+256": ("Uganda", "eu"),
    "+380": ("Ukraine", "eu"),
    "+971": ("United Arab Emirates", "as"),
    "+1": ("United States", "us"),
    "+598": ("Uruguay", "us"),
    "+998": ("Uzbekistan", "as"),
    "+678": ("Vanuatu", "us"),
    "+58": ("Venezuela", "us"),
    "+84": ("Vietnam", "as"),
    "+685": ("Western Samoa", "us"),
    "+1340": ("Wilk Islands", "as"),
    "+967": ("Yemen", "as"),
    "+260": ("Zambia", "eu"),
    "+263": ("Zimbabwe", "eu"),
}


def infer_country_code(username: str, fallback: str = "+86") -> str:
    if not username.startswith("+"):
        return fallback
    matches = [code for code in REGIONS if username.startswith(code)]
    return max(matches, key=len) if matches else fallback